---
title: "PlottingFunctions package"
output:
  html_document:
    df_print: paged
    toc: true
   # theme: paper
  pdf_document: default
---

# Package installation


The package can be installed via github:

```{r}
library(devtools)
if(!require(plottingFunctions)) {
  devtools::install_github("mariavica/plottingFunctions", ref="master", build_vignettes = FALSE)
}
library(plottingFunctions)
```

# HiC related functions:

## map.plot
This is how variables are: ``map`` variable refers to the (missing values are allowed) and ``ref`` is a bedfile with the regions that you want to plot.

```{r include=FALSE}
data(map)
data(ref)
```

```{r}
map[1000:1004,]
```

```{r}
head(ref)
```

The plot should look like this:
```{r}
data(map)
data(ref)
map.plot(ref=ref,map=map, expand=5, show.orig = TRUE)
```


## plotTwoTrends


## selectAB


## correctAB


# Miscellania

## get.chr

Select the desired character

```{r}
get.chr(c('a-b-c-d'), sep='-', pos=2)
```


## GOheatmap


```{r}

genes <-list( a=c('Fgfr3'), b=c('Dyrk1a','Ctcf'))

genes <-c('Fgfr3','Dyrk1a','Ctcf')
cluster <- c(1,2,2)

GOheatmap(genes=genes , cluster=cluster, organism="mouse")

```



